### ISSUE TITLE
False positives with virustotal for api-ms-win-core-path-l1-1-0

### ISSUE THREAD

**Issue by Illasera** [nalexandru/api-ms-win-core-path-HACK#7]
Added the following link : https://www.virustotal.com/gui/file/a1f02f8f2b90f89d0bfae554d2ebd61d07c7454eabbc53236738143180e030ce

Now, I am aware as you wrote that it is a hacked version, But any idea what could trigger the false positives?
What exactly is the purpose of this hacked .dll and how does it works in simplified terms?

(Yes, you did provide a summary in the main github project page but more info would be welcomed).

.DLL Release version : Current release (0.3.1)

**Comment by nalexandru** [comment]
I don't know what could trigger the false positives.
As for the purpose, api-ms-win-core-path-l1-1-0, was added in Windows 8 and is required for Python 3.9 and newer (it imports PathCchCanonicalizeEx, PathCchCombineEx and PathCchSkipRoot from it). This project provides a working version of this library for Windows 7.

**Comment by Illasera** [comment]
Thank you sir.

**Comment by nalexandru** [comment]
The DLL i uploaded was compiled with VS2019. Newer versions of VS produce larger executables.
As for the build settings, the VS project and solution used to build it are in the repository.

I no longer have the pdb files from the build that i uploaded or VS2019 installed so i've rebuilt it with VS2022, version 17.0.6, and the resulting binary has the same false positives as the original one. It is a bit larger than the 2019 version, 115kb for 64bit release.
You can find the binaries with pdb files here: https://1drv.ms/u/s!AhpnXywMA4U1mT_9pGBtVKSn6AvJ?e=LNuP4e

Try to compile the code with VS2019 or VS2022 with the included solution file. It should produce a binary with the same false positives.

Scan results for the new binary:

https://www.virustotal.com/gui/file/127c48034db453b2bd6db1db44d8647b18e388976be0acb1744de4f7aa2165e1/detection

**Comment by Illasera** [comment]
Through dependencywalker at least, i couldn't find any telemetry calls to the file in question (in the original post)

![ScreenShot3888](https://user-images.githubusercontent.com/1932973/153773697-d3a0b4f6-7ccb-4785-87cd-49145efead90.jpg)

mind btw, that for your new file with VS2022, all the portscanning and eventlog clearning warnings disappeared, we have to make sure that it was indeed VS 2019 that caused this issue, I will see i i can get running copy of VS2019 and replicate it.

**Comment by nalexandru** [comment]
Dependency walker (i assume you mean depends.exe) will not show you functions that are not exported from the dll, so i doubt you would find anything with it. Feel free to dissasemble/decompile the binary to check the code in it.

I took a closer look at the virustotal sandbox runs from the original link you posted.

In the "VirusTotal Zenbox" sandbox, the host application for the DLL crashed, because a Windows Error Report was created. The network communication detected in this sandbox that matched the "TAG_LOG_PKT" rule was to the IP 52.225.188.83, which, according to VirusTotal, belongs to Microsoft and it was resolved on 2021-07-24 as umwatsonc.telemetry.microsoft.us.
![tag_log_pkt](https://user-images.githubusercontent.com/9295849/153785175-f1e38428-eae9-465c-aaa8-8232d65faa17.PNG)

VirusTotal report for 52.255.188.83: https://www.virustotal.com/gui/ip-address/52.255.188.83

The ip addres 52.255.188.83 is contacted in a sandbox run for a signed Microsoft DLL (that also caused a crash, generating a WER), matching the same TAG_LOG_PKT rule, as can be seen here: https://www.virustotal.com/gui/file/003a4c4b4716b08f059f4a692fecb3c0fc2fc10334cddbc66d16dc8c7f29c5b9/behavior/VirusTotal%20ZenBox

I believe this network access is the result of the WER that was generated being sent to Microsoft.

The "(port_scan) UDP portsweep" was triggered for the ip 8.8.8.8 which is Google's public DNS server. I don't know how rule works, but i suspect this was triggered by a DNS lookup executed in the sandbox, probably for domain that points to 52.255.188.83.
![portsweep](https://user-images.githubusercontent.com/9295849/153785140-99823e74-d647-4b16-883f-5f922d113535.PNG)

This rule is not matched by the signed Microsoft DLL. If the false positive was triggered by a DNS lookup, the results of that might've been cached.

The other 2 sandboxes did not record any network communication.
The "Zenbox" sandbox has the same crash as "VirusTotal Zenbox". If the WER was sent, the network activity was not recorded.
The "C2AE" sandbox has some registry access to WMI, which i doubt happened because of this dll. It was more likely caused by the invocation of wmiadap.exe and/or wmiprvse.exe as seen in the Process Tree.
![proc_tree](https://user-images.githubusercontent.com/9295849/153785672-e52c61de-7d96-4c86-a417-77b857592727.PNG)

I don't see any evidence to support the claim that it's "ransomware malware" based on the sandbox activity. From what i see in the sandbox activity, the false positives were triggered by VS telemetry and/or a WER being sent to Microsoft

It might've been a preview release of Visual Studio that was used to compile that DLL if the results can't be reproduced with a stable release.

The file that is in the Releases page, that generated the false positives, is not malicious. If you don't trust it, please use your own build.

**Comment by Illasera** [comment]
Well, based on your research, I do tend to agree with you, I am satisfied with the answer.

Keep up the good work , And i am using my own build (Thanks to your code) but i will still encourage people to use your hack (fix) .dll.

My version uses cygwin and i assume its not ideal.
